# MetaMask locators (CSS / test-id selectors)
TERMS_CHECKBOX = "#onboarding__terms-checkbox"
IMPORT_WALLET_BTN = "text=Import an existing wallet"
I_AGREE_BTN = "text=I agree"
PASSWORD_INPUT = "[data-testid='create-password-new']"
CONFIRM_PASSWORD_INPUT = "[data-testid='create-password-confirm']"
PASSWORD_TERMS_CHECKBOX = "[data-testid='create-password-terms']"
IMPORT_BTN = "[data-testid='create-password-import']"
DONE_BTN = "[data-testid='onboarding-complete-done']"
NEXT_BTN = "[data-testid='pin-extension-next']"
DONE_PIN_BTN = "[data-testid='pin-extension-done']"
NOT_NOW_BTN = "[data-testid='not-now-button']"
CLOSE_POPUP_BTN = ".page-container__header-close"
RECEIVE_BTN = "[data-testid='eth-overview-receive']"
QR_ADDRESS = ".qr-code__address-segments"
